# Generated by Django 4.0 on 2023-11-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_pid_product_rating_profile_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
