# Generated by Django 4.0 on 2023-12-03 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_user_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_searchs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchs', models.CharField(max_length=100)),
                ('userobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
