# Generated by Django 4.0 on 2024-02-03 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_cart_items_cart_item_alter_cart_cartref'),
    ]

    operations = [
        migrations.CreateModel(
            name='ucart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.DeleteModel(
            name='cart',
        ),
    ]
