# Generated by Django 4.0 on 2024-02-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_ucart_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_orders',
            name='expected_delivery',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user_orders',
            name='order_status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
